stages:
  load:
    cmd: python -m src.data.load_data
    deps:
      - src/data/load_data.py
      - data/raw
    outs:
      - data/intermediate/dataset.pkl

  preprocess:
    cmd: python -m src.data.preprocessing
    deps:
      - src/data/preprocessing.py
      - data/raw
    outs:
      - data/processed/train
      - data/processed/val
      - data/processed/test

  train:
    cmd: python -m src.models.train
    deps:
      - src/models/train.py
      - data/processed/train
      - data/processed/val
    outs:
      - models

  evaluate:
    cmd: python -m src.models.evaluate
    deps:
      - src/models/evaluate.py
      - models
    outs:
      - reports/metrics.json
